# Generated by Django 4.2.4 on 2023-08-12 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='customer',
        ),
    ]
